#!/bin/bash
echo ""
echo "  🦅  FLY LABOUR - Hệ thống tuyển dụng lao động quốc tế"
echo "  ====================================================="
echo ""
echo "  📦  Đang cài đặt dependencies..."
npm install
echo ""
echo "  ✅  Cài đặt hoàn tất!"
echo ""
echo "  🚀  Chạy lệnh sau để khởi động:"
echo "      npm run dev"
echo ""
echo "  🌐  Truy cập:"
echo "      Website:  http://localhost:5173"
echo "      Admin:    http://localhost:5173/admin"
echo ""
echo "  🔑  Tài khoản demo:"
echo "      Admin → admin@flylabour.com / Admin@123"
echo "      User  → user@example.com    / User@123"
echo ""
